const main=document.getElementById('main'),bar=document.getElementById('bar'),count=document.getElementById('count'),unlock=document.getElementById('unlock');
let discoveries=new Set(),quizDone=false,dreamDone=false,puzzleDone=false,memoryDone=false,answers=[];
const backgroundMusic=document.getElementById('backgroundMusic');
document.getElementById('start').onclick=()=>{backgroundMusic.volume=.35;backgroundMusic.play().catch(()=>{});main.classList.add('open');activateStage(1)};function activateStage(n){document.querySelectorAll('.stage').forEach(s=>s.classList.remove('active'));const next=document.getElementById('stage'+n);next.classList.add('active');setTimeout(()=>next.scrollIntoView({behavior:'smooth',block:'start'}),80)}
const observer=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.12});document.querySelectorAll('.reveal').forEach(e=>observer.observe(e));
function update(){const n=discoveries.size+(quizDone?1:0)+(dreamDone?1:0)+(puzzleDone?1:0)+(memoryDone?1:0);bar.style.width=(n/7*100)+'%';count.textContent=n+' de 7 descobertas';if(n===7){unlock.disabled=false;document.getElementById('finalTitle').textContent='A mensagem está pronta';document.getElementById('lockedNote').textContent='Vc encontrou cada pedacinho da surpresa.'}}
document.querySelectorAll('[data-discovery]').forEach((card,i)=>card.onclick=()=>{card.classList.add('done');discoveries.add(i);burst(card);update();if(discoveries.size===3)document.getElementById('starsContinue').classList.add('show')});
const questions=[...document.querySelectorAll('.question')];document.querySelectorAll('.option').forEach(btn=>btn.onclick=()=>{answers.push(btn.textContent);const current=btn.closest('.question'),index=questions.indexOf(current);current.classList.remove('active');if(index<questions.length-1){questions[index+1].classList.add('active')}else{quizDone=true;document.querySelector('.quiz-result').classList.add('show');document.getElementById('quizText').textContent='Vc escolheu: '+answers.join(' · ')+'. Cada escolha deixou essa história ainda mais única.';update();document.getElementById('quizContinue').classList.add('show')}});
const selected=new Set();document.querySelectorAll('.dream').forEach(btn=>btn.onclick=()=>{btn.classList.toggle('selected');btn.classList.contains('selected')?selected.add(btn.textContent):selected.delete(btn.textContent);dreamDone=selected.size>0;document.getElementById('dreamContinue').disabled=!dreamDone;document.getElementById('dreamOutput').textContent=selected.size?'Nossa cápsula: '+[...selected].join(' · '):'O futuro começa com uma escolha ✦';update()});
unlock.onclick=()=>{const letter=document.getElementById('letter');letter.classList.add('show');unlock.style.display='none';finalCelebration(letter);setTimeout(()=>letter.scrollIntoView({behavior:'smooth',block:'center'}),250)};
function finalCelebration(el){const r=el.getBoundingClientRect();for(let i=0;i<46;i++){setTimeout(()=>{const h=document.createElement('span');h.className='final-heart';h.textContent='❤';h.style.left=(r.left+Math.random()*r.width)+'px';h.style.top=(Math.min(innerHeight-35,r.top+r.height*.72))+'px';h.style.fontSize=(12+Math.random()*22)+'px';h.style.color=i%3?'#e60023':'#ff477e';h.style.setProperty('--hx',(Math.random()*300-150)+'px');h.style.setProperty('--hy',(-150-Math.random()*330)+'px');h.style.setProperty('--hr',(Math.random()*220-110)+'deg');h.style.setProperty('--time',(1.7+Math.random()*1.25)+'s');document.body.appendChild(h);setTimeout(()=>h.remove(),3200)},i*32)}}
function burst(el,total=18){const r=el.getBoundingClientRect();for(let i=0;i<total;i++){const p=document.createElement('span');p.className='particle';p.textContent=i%3?'✦':'●';p.style.left=(r.left+r.width/2)+'px';p.style.top=(r.top+r.height/2)+'px';p.style.color=i%2?'#ffd890':'#ff74a8';p.style.setProperty('--x',(Math.random()*260-130)+'px');p.style.setProperty('--y',(Math.random()*220-140)+'px');document.body.appendChild(p);setTimeout(()=>p.remove(),1250)}}
function bearBurst(el,total=22){const r=el.getBoundingClientRect();for(let i=0;i<total;i++){const p=document.createElement('span');p.className='particle';p.textContent='❤';p.style.left=(r.left+r.width/2)+'px';p.style.top=(r.top+r.height/2)+'px';p.style.color=i%2?'#e60023':'#ff1744';p.style.fontSize=(14+Math.random()*14)+'px';p.style.textShadow='0 2px 5px #8b001c55';p.style.setProperty('--x',(Math.random()*220-110)+'px');p.style.setProperty('--y',(Math.random()*210-145)+'px');document.body.appendChild(p);setTimeout(()=>p.remove(),1250)}}
document.getElementById('dreamContinue').onclick=()=>{if(dreamDone)activateStage(4)};
document.getElementById('starsContinue').onclick=()=>activateStage(2);
document.getElementById('quizContinue').onclick=()=>activateStage(3);
document.getElementById('puzzleContinue').onclick=()=>activateStage(5);
document.getElementById('memoryContinue').onclick=()=>activateStage(6);
const puzzle=document.getElementById('puzzle'),puzzleStatus=document.getElementById('puzzleStatus'),movesEl=document.getElementById('moves');let order=[],picked=null,moves=0;
function shufflePuzzle(){order=[1,2,3,4,5,6,7,8,9];do{for(let i=order.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[order[i],order[j]]=[order[j],order[i]]}}while(order.every((n,i)=>n===i+1));picked=null;moves=0;puzzleDone=false;renderPuzzle();update()}
function renderPuzzle(){puzzle.innerHTML='';order.forEach((n,i)=>{const b=document.createElement('button');b.className='piece'+(n===i+1?' correct':'')+(picked===i?' chosen':'');b.textContent=n;b.type='button';b.setAttribute('aria-label','Peça '+n);b.onclick=()=>pickPiece(i);puzzle.appendChild(b)});movesEl.textContent=moves+' movimento'+(moves===1?'':'s')}
function pickPiece(i){if(puzzleDone)return;if(picked===null){picked=i;renderPuzzle();return}if(picked===i){picked=null;renderPuzzle();return}[order[picked],order[i]]=[order[i],order[picked]];picked=null;moves++;renderPuzzle();if(order.every((n,j)=>n===j+1)){puzzleDone=true;puzzleStatus.textContent='Vc montou! O desafio secreto foi desbloqueado ✦';puzzle.querySelectorAll('.piece').forEach(p=>p.classList.add('correct'));document.getElementById('challenge2').classList.add('unlocked');document.getElementById('memoryStart').disabled=false;document.getElementById('memoryStatus').textContent='Pronta? Observe com atenção.';burst(puzzle,35);update();document.getElementById('puzzleContinue').classList.add('show')}}
document.getElementById('resetPuzzle').onclick=shufflePuzzle;shufflePuzzle();
const memoryButtons=[...document.querySelectorAll('.memory-btn')],memoryStatus=document.getElementById('memoryStatus'),memoryStart=document.getElementById('memoryStart');let memorySequence=[],memoryInput=[],memoryPlaying=false;
function makeSequence(){memorySequence=Array.from({length:3},()=>Math.floor(Math.random()*4));memoryInput=[];memoryPlaying=true;memoryStart.disabled=true;memoryButtons.forEach(b=>b.disabled=true);memoryStatus.textContent='Observe a sequência...';memorySequence.forEach((value,i)=>setTimeout(()=>{const b=memoryButtons[value];b.classList.add('flash');setTimeout(()=>b.classList.remove('flash'),420)},850+i*850));setTimeout(()=>{memoryPlaying=false;memoryButtons.forEach(b=>b.disabled=false);memoryStatus.textContent='Agr repita a ordem!'},700+memorySequence.length*850)}
memoryStart.onclick=()=>{if(memoryDone)return;if(!puzzleDone){memoryStatus.textContent='Termine o quebra-cabeça primeiro.';return}makeSequence()};
memoryButtons.forEach((b,i)=>b.onclick=()=>{if(memoryPlaying||!puzzleDone||memoryDone)return;b.classList.add('flash');setTimeout(()=>b.classList.remove('flash'),180);memoryInput.push(i);const pos=memoryInput.length-1;if(memoryInput[pos]!==memorySequence[pos]){memoryInput=[];memoryStatus.textContent='Quase! Toque em “Mostrar sequência” e tente dnv.';memoryStart.disabled=false;memoryButtons.forEach(x=>x.disabled=true);return}if(memoryInput.length===memorySequence.length){memoryDone=true;memoryStatus.textContent='Sequência perfeita! A mensagem final foi liberada ✦';memoryButtons.forEach(x=>x.disabled=true);memoryStart.style.display='none';burst(document.getElementById('memoryBoard'),40);update();document.getElementById('memoryContinue').classList.add('show')}});
function bearRain(){for(let i=0;i<28;i++){setTimeout(()=>{const h=document.createElement('span');h.className='rain-heart';h.textContent='❤';h.style.left=(Math.random()*96+2)+'vw';h.style.fontSize=(15+Math.random()*22)+'px';h.style.setProperty('--rain-time',(1.35+Math.random()*.9)+'s');document.body.appendChild(h);setTimeout(()=>h.remove(),2500)},i*38)}}
function bearHop(el){el.classList.remove('tap-hop');void el.offsetWidth;el.classList.add('tap-hop');const r=el.getBoundingClientRect();for(let i=0;i<18;i++){const h=document.createElement('span');h.className='trail-heart';h.textContent='❤';h.style.left=(r.left+r.width/2)+'px';h.style.top=(r.top+r.height/2)+'px';h.style.fontSize=(12+Math.random()*15)+'px';h.style.setProperty('--tx',(Math.random()*150-75)+'px');h.style.setProperty('--ty',(-45-Math.random()*125)+'px');h.style.setProperty('--tr',(Math.random()*180-90)+'deg');document.body.appendChild(h);setTimeout(()=>h.remove(),1450)}setTimeout(()=>el.classList.remove('tap-hop'),800)}
function bearBigHeart(el){const h=document.createElement('span');h.className='big-heart';h.textContent='❤';document.body.appendChild(h);bearBurst(el,10);setTimeout(()=>h.remove(),1750)}
const bearEffects=[el=>bearBurst(el,26),()=>bearRain(),el=>bearHop(el),el=>bearBigHeart(el)];
document.querySelectorAll('.user-bear').forEach((b,i)=>b.onclick=()=>bearEffects[i](b));
update();
